config:
  backup: true
  create: true
  dotpath: punkto
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_profile:
    src: profile
    dst: ~/.profile
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_tmux:
    src: tmux
    dst: ~/.tmux
profiles:
  luzifer:
    dotfiles:
    - ALL
  stiller:
    dotfiles:
    - ALL
