config:
  backup: true
  create: true
  dotpath: punkto
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_profile:
    src: profile
    dst: ~/.profile
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  luzifer:
    dotfiles:
      - ALL
  stiller:
    dotfiles:
      - ALL
